spring:
  application:
    name: lawhub-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/lawhub
    username: postgres
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT ??
jwt:
  secret-key: 'WmR2YnBnb3RsZXZoaGJ2cmtxN2FiYmNtYXNkZmdoa2xqYXNkZmY='
  expiration-time: 86400000 # 24 hours in milliseconds

springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
  info:
    title: LawHub API Documentation
    description: This is the API documentation for the LawHub application.
    version: 1.0.0

server:
  port: 8080